In [1]:
# Importing Packages
import cv2
import numpy as np

# Images & Windows in OpenCV
The code snippets in this section below are for the corresponding section of the article. 

## Creating Windows

In [2]:
# Creating a Normal Window
cv2.namedWindow('Normal', cv2.WINDOW_NORMAL)

In [ ]:
# Creating an Autosized Window
cv2.namedWindow('Autosize', cv2.WINDOW_AUTOSIZE)

## Displaying Windows

In [3]:
# Display window for five seconds or till a key is pressed
cv2.namedWindow('Normal', cv2.WINDOW_NORMAL)
cv2.waitKey(5000)

227

In [2]:
# Display window until a key is pressed
cv2.namedWindow('Normal II', cv2.WINDOW_NORMAL)
cv2.waitKey(0)

113

## Destroying Windows

In [7]:
# Destroy a single window by window name
cv2.namedWindow('Sample One', cv2.WINDOW_NORMAL)
cv2.waitKey(5000)
cv2.destroyWindow('Sample One')

In [8]:
# Destroy all windows regardless of window name
cv2.namedWindow('Sample Two', cv2.WINDOW_AUTOSIZE)
cv2.namedWindow('Sample Three', cv2.WINDOW_NORMAL)
cv2.waitKey(5000)
cv2.destroyAllWindows()

## Resizing Windows

In [102]:
# Resize window to desired dimension; 600 x 300 in this case
cv2.namedWindow('image', cv2.WINDOW_AUTOSIZE)
cv2.resizeWindow('image', 600, 300)
cv2.waitKey(5000)
cv2.destroyAllWindows()

## Reading Images

In [3]:
# Read an image
image = cv2.imread("images/testimage.jpg")
# Print the pixels that make up the image as matrices
print(image)

[[[255 204   0]
  [255 204   0]
  [255 204   0]
  ..., 
  [255 204   0]
  [255 204   0]
  [255 204   0]]

 [[255 204   0]
  [255 204   0]
  [255 204   0]
  ..., 
  [255 204   0]
  [255 204   0]
  [255 204   0]]

 [[255 204   0]
  [255 204   0]
  [255 204   0]
  ..., 
  [255 204   0]
  [255 204   0]
  [255 204   0]]

 ..., 
 [[255 204   0]
  [255 204   0]
  [255 204   0]
  ..., 
  [254 203   0]
  [254 204   0]
  [255 205   0]]

 [[255 204   0]
  [255 204   0]
  [255 204   0]
  ..., 
  [254 204   0]
  [254 204   0]
  [255 205   0]]

 [[255 204   0]
  [255 204   0]
  [255 204   0]
  ..., 
  [254 204   0]
  [254 204   0]
  [255 205   0]]]


In [4]:
# Read an image in grayscale mode
image = cv2.imread("./images/testimage.jpg", cv2.IMREAD_GRAYSCALE)
# Print the pixels that make up the image as matrices
print(image)

[[149 149 149 ..., 149 149 149]
 [149 149 149 ..., 149 149 149]
 [149 149 149 ..., 149 149 149]
 ..., 
 [149 149 149 ..., 148 148 149]
 [149 149 149 ..., 148 148 149]
 [149 149 149 ..., 148 148 149]]


## Displaying Images

In [5]:
# Read and display an image in BGR and Grayscale modes
image = cv2.imread('./images/testimage.jpg')
cv2.namedWindow('Cars', cv2.WINDOW_NORMAL)
cv2.imshow('Cars', image)
cv2.waitKey(5000)
image = cv2.imread('./images/testimage.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imshow('Cars', image)
cv2.waitKey(5000)
cv2.destroyWindow('Cars')

## Saving Images

In [18]:
# Read and save image in grayscale mode
gray_image = cv2.imread("./images/testimage.jpg", cv2.IMREAD_GRAYSCALE)
cv2.imwrite("./images/grayimage.jpg", gray_image)

# Editing Images with OpenCV
The code snippets in this section below are for the corresponding section of the article.

## Switching Color Modes

In [6]:
# Convert image from BGR to YCrCb using the integer value 36
image = cv2.imread("images/testimage.jpg")
image_mode = cv2.cvtColor(image, 36)
cv2.imshow("Cars", image_mode)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [14]:
# Convert image from BGR to Grayscale using the constant attribute COLOR_BGR2GRAY
image = cv2.imread("./images/testimage.jpg")
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Cars", image_gray)
cv2.waitKey(5000)
cv2.destroyAllWindows()

## Editing Pixel Values

In [15]:
# Check image dimensions
image = cv2.imread("./images/testimage.jpg")
print(image.shape)
image_gray = cv2.imread("./images/testimage.jpg", cv2.IMREAD_GRAYSCALE)
print(image_gray.shape)

(720, 1280, 3)
(720, 1280)


In [7]:
# Fill left half of image with black pixels
image = cv2.imread("./images/testimage.jpg", cv2.IMREAD_GRAYSCALE)
edited_image = image.copy()
edited_image[:, :640] = 0
cv2.namedWindow('Cars',cv2.WINDOW_NORMAL)
cv2.imshow('Cars', edited_image)
cv2.waitKey(5000)
cv2.destroyWindow('Cars')

## Joining images

In [8]:
# Join three images horizontally
image = cv2.imread("./images/logo.jpg")
hcombine = np.hstack((image, image, image))
cv2.imshow("Cars Combined", hcombine)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [3]:
# Join three images vertically
image = cv2.imread("./images/logo.jpg")
vcombine = np.vstack((image, image, image))
cv2.imshow("Cars Combined", vcombine)
cv2.waitKey(5000)
cv2.destroyAllWindows()

## Accessing Color Channels

In [24]:
# Eliminate Blue and Green channels by making them Black
image = cv2.imread("./images/logo.jpg")
image_r = image.copy()
image_r[:, :, 0] = 0
image_r[:, :, 1] = 0
cv2.imshow("Red Channel", image_r)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [9]:
# Extract individual channels and join the resulting images
image = cv2.imread("./images/logo.jpg")
image_b = image.copy()
image_b[:, :, 1] = 0
image_b[:, :, 2] = 0
image_g = image.copy()
image_g[:, :, 0] = 0
image_g[:, :, 2] = 0
image_r = image.copy()
image_r[:, :, 0] = 0
image_r[:, :, 1] = 0
numpy_horizontal = np.hstack((image_b, image_g, image_r))
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 800, 800)
cv2.imshow("image", numpy_horizontal)
cv2.waitKey(5000)
cv2.destroyAllWindows()

## Cropping Images

In [10]:
# Crop an image using desired pixel values
image = cv2.imread('./images/testimage.jpg')
cv2.namedWindow('Cars',cv2.WINDOW_NORMAL)
edited_image = image.copy()
edited_image = edited_image[30:190, 205:560]
cv2.imshow('Cars', edited_image)
cv2.waitKey(5000)
cv2.destroyWindow('Cars')

## Drawing on Images

In [11]:
# Put text on an image
image = cv2.imread('./images/croppedimage.jpg')
font = cv2.FONT_HERSHEY_COMPLEX
cv2.putText(image,'LinuxHint',(85,32), font, 0.8,(0, 0, 0),1)
cv2.namedWindow('Car',cv2.WINDOW_NORMAL)
cv2.imshow('Car', image)
cv2.waitKey(5000)
cv2.destroyWindow('Car')

In [12]:
# Draw a line on an image
image = cv2.imread('./images/testimage.jpg')
cv2.line(image,(0,380),(1280,380),(0,255,0),10)
cv2.namedWindow('Car',cv2.WINDOW_NORMAL)
cv2.imshow('Car', image)
cv2.waitKey(5000)
cv2.destroyWindow('Car')

In [13]:
# Drawing a circle on an image
image = cv2.imread('./images/testimage.jpg')
cv2.circle(image,(110,125), 100, (0,0,255), -1)
cv2.circle(image,(1180,490), 80, (0,0,0), 1)
cv2.namedWindow('Car',cv2.WINDOW_NORMAL)
cv2.imshow('Car', image)
cv2.waitKey(5000)
cv2.destroyWindow('Car')

## Applying Image Filters

In [17]:
# Applying the Gaussian Blur image filter
image = cv2.imread('./images/testimage.jpg')
blurred = cv2.GaussianBlur(image, (5,5), 0)
cv2.namedWindow('Cars', cv2.WINDOW_NORMAL)
cv2.imshow('Cars', blurred)
cv2.waitKey(5000)
blurred = cv2.GaussianBlur(image, (25,25), 0)
cv2.namedWindow('Cars', cv2.WINDOW_NORMAL)
cv2.imshow('Cars', blurred)
cv2.waitKey(5000)
cv2.destroyWindow('Cars')

# Videos in OpenCV
The code snippets in this section below are for the corresponding section of the article.

## Loading Videos

In [33]:
# Load a video
video = cv2.VideoCapture("./videos/testvideo.mp4")

## Displaying Videos

In [35]:
# Display video at a fast pace, and quit display if the key "q" is pressed
video = cv2.VideoCapture('./videos/testvideo.mp4')
while(video.isOpened()):
    ret, image = video.read()
    if image is None:
        break
    cv2.imshow('Video Frame', image)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video.release()
cv2.destroyAllWindows()

In [ ]:
# Display video at a slow pace, and quit display if the key "q" is pressed
video = cv2.VideoCapture('./videos/testvideo.mp4')
while(video.isOpened()):
    ret, image = video.read()
    if image is None:
        print(ret)
        break
    cv2.imshow('Video Frame', image)
    if cv2.waitKey(40) & 0xFF == ord('q'):
        break

video.release()
cv2.destroyAllWindows()

## Accessing the WebCam

In [37]:
# Activate webcam and display video in real time
video = cv2.VideoCapture(0)
while(video.isOpened()):
    ret, image = video.read()
    cv2.imshow('Live Cam', image)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video.release()
cv2.destroyAllWindows()

## Recording Videos

In [38]:
# Record videos from the webcam
video = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc('X','V','I','D')
writer = cv2.VideoWriter('out.avi',fourcc, 15.0, (640,480))
while(video.isOpened()):
    ret, image = video.read()
    writer.write(image)
    cv2.imshow('frame',image)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video.release()
writer.release()
cv2.destroyAllWindows()